site_name: PainTown
theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/logo.png
  palette:
    # Palette toggle for dark mode
    #- media: "(prefers-color-scheme: dark)"
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    #- media: "(prefers-color-scheme: light)"
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
  icon:
    admonition:
      quote: octicons/video-24
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kazzmir
      name: Follow @kazzmir
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
  - search
#  - git-authors:
#      show_contribution: true
#      show_email_address: false
#      enabled: true