site_name: PainTown
theme:
  name: material
  logo: assets/logo.png
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    #- media: "(prefers-color-scheme: light)"
    #  scheme: default
    #  toggle:
    #    icon: material/brightness-7 
    #    name: Switch to dark mode
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kazzmir
      name: Follow @kazzmir